version: "3.9"

services:
  db:
    image: postgres:16
    container_name: task_management-db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret123
      POSTGRES_DB: task_management
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d task_management || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 10

  app:
    build: .
    container_name: task_management-app
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_DATABASE: task_management
      DB_USERNAME: admin
      DB_PASSWORD: secret123
    command: bash -c "php artisan migrate && php artisan db:seed && php artisan serve --host=0.0.0.0 --port=8000"

volumes:
  pgdata:

